### ISSUE TITLE
Please create a complete demo program

### ISSUE THREAD

**Issue by sandeep-datta** [bburdette/windowkeys#1]
Hi, I think putting together a demo program to show how this module can be used will be far more helpful than a written description in the readme.

**Comment by bburdette** [comment]
agree.  until such time as that's available, you can look at some projects that use it:

https://github.com/InterstitialTech/timeclonk

https://github.com/bburdette/zknotes

In both of those, look at index.html and Main.elm for a starting place.

**Comment by bburdette** [comment]
example published!  ellie linked in the readme.
